import "./globals.css";
import { Source_Sans_3 } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs/app-beta";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Source_Sans_3({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en" className={lato.className}>
        <body>
          {/* <Providers>{children}</Providers> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
